version: "3.8"
services:
  jvlcart-backend:
    build:
      context: "."
      dockerfile: "Dockerfile"
    restart: always
    ports:
     - "8080:8080"
  jvlcart-db:
    image: mysql:8.0
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: ${DB_PASS}
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASS}
    env_file: 
    - .env